### PR TITLE
NameGenerator functional interface, cleanups

### PR DESCRIPTION
**Pull request by wallstop**
* Functional interfaces. I really hate passing around instances of the java Random class. Much preferred [ThreadLocalRandom](java-performance.info/java-util-random-java-util-concurrent-threadlocalrandom-multithreaded-environments/), or, if I want higher quality, a [PCG generator](http://www.pcg-random.org/). Never never Random. To facilitate this, we can proxy randoms by specifying a more abstract implementation of what we really want, which is only a function that takes a maxRange param and returns a value from [0, maxRange)

This way, users can pass in their own random impls, or just use the existing method overloads.

* Nitpick perf improvements / clarity

### CODE REVIEW

**Comment by Valkryst** [comment]
Interesting alterations, I'll need to look into IntUnaryOperator and setting a class as final later on, but it all appears to function the same as the original code. Merging.

**Comment by wallstop** [comment]
Feel free to push back on anything you're not 100% happy with! I'm working on a C# port for my own edification and use, so I'll likely be doing PRs and backporting things into Java. Thanks for the merges :)

**Comment by Valkryst** [comment]
It's all looking fine for now. Could you look over the unit tests and ensure that the "IntUnaryOperator" is being used correctly?

I've had to make a few assumptions about it's use, and it does seem to be working, but I'm unsure if it's being used in the way you originally intended.

**Comment by wallstop** [comment]
No problem!

What you have works! However, it might not be the cleanest approach. Here's what I'm seeing:

`final IntUnaryOperator randomInRange = (value) -> new Random(System.nanoTime()).nextInt(value);`

Every method invocation, this will create a new Random object based on System nanotime, call nextInt(value), then throw the random away (or really, off to get collected at next GC)

Some alternatives:

`Random random = new Random(System.nanoTime());
final IntUnaryOperator randomInRange = random::nextInt;`

or

`Random random = new Random(System.nanoTime());
final IntUnaryOperator randomInRange = value -> random.nextInt(value);` (should end up being the same bytecode as the above)

Or even

`final IntUnaryOperator randomInRange = ThreadLocalRandom.current()::nextInt`

**Comment by Valkryst** [comment]
Ah, thanks for clearing that up for me. I had a fairly difficult time actually finding information on how the IntUnaryOperator works.

I'll have the test cases altered to use the final example that you've given and the README to include a mostly copy-paste from what you've shown.

**Comment by wallstop** [comment]
No problem! IntUnaryOperator is part of the [sweet new java 8 functional interfaces](https://docs.oracle.com/javase/8/docs/api/java/util/function/package-summary.html). If you aren't super familiar with them, I found [this oreilly post](https://www.oreilly.com/learning/java-8-functional-interfaces) to be a pretty decent resource.

**Pull request merged**
